language: python
python:
  - "3.6"
env:
  TRANSLATE_ENGINE: naver
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - flake8 .
script:
  - coverage run --source=./ -m py.test
after_success:
  - coveralls
